// File generated by FlutterFire CLI
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // resto del código
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Devuelve la configuración Firebase de la plataforma actual
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgg3I365LMqp2RvBL8o3SwTAeRNn6GCCw',
    appId: '1:727116770605:web:769c6cb8020851d90637a4',
    messagingSenderId: '727116770605',
    projectId: 'filmapp-ac786',
    authDomain: 'filmapp-ac786.firebaseapp.com',
    storageBucket: 'filmapp-ac786.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5buAru-rneDY7GaCXOD4FbJa6SW4Lx4Y',
    appId: '1:727116770605:android:8f444452746845590637a4',
    messagingSenderId: '727116770605',
    projectId: 'filmapp-ac786',
    storageBucket: 'filmapp-ac786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX9sjNTr0r-vA1b08MX3HMIOnqPRZKsFA',
    appId: '1:727116770605:ios:e06e47f07f859e0c0637a4',
    messagingSenderId: '727116770605',
    projectId: 'filmapp-ac786',
    storageBucket: 'filmapp-ac786.firebasestorage.app',
    iosBundleId: 'com.kike.filmApp',
  );
}
